server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: microservicedb
    password: password
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka