server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
    username: microservicedb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true